---
apiVersion: v1
kind: Service
metadata:
  name: treasure-hunt-entrypoint
  namespace: default
spec:
  selector:
    serviceType: treasure-hunt
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort