apiVersion: v1
kind: ConfigMap
metadata:
  name: treasure-hunt-config
  namespace: default
data:
  treasurehunt.max.attempts: "5"
---
apiVersion: v1
kind: Secret
metadata:
  name: treasure-hunt-secrets
type: Opaque
data:
  treasure.location.x: MTQ=
  treasure.location.y: MTc=
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: treasure-hunt
  labels:
    serviceType: treasure-hunt
spec:
  replicas: 1
  template:
    metadata:
      name: treasure-hunt
      labels:
        serviceType: treasure-hunt
    spec:
      containers:
        - name: treasure-hunt
          image: treasurehunt:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 8080
          env:
          - name: JAVA_OPTS
            value: -Xmx64m -Xms64m
          - name: TREASUREHUNT_MAX_ATTEMPTS
            valueFrom:
              configMapKeyRef:
                name: treasure-hunt-config
                key: treasurehunt.max.attempts
          - name: TREASURE_LOCATION_X
            valueFrom:
              secretKeyRef:
                name: treasure-hunt-secrets
                key: treasure.location.x
          - name: TREASURE_LOCATION_Y
            valueFrom:
              secretKeyRef:
                name: treasure-hunt-secrets
                key: treasure.location.y
---
apiVersion: v1
kind: Service
metadata:
  name: treasure-hunt-entrypoint
  namespace: default
spec:
  selector:
    serviceType: treasure-hunt
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort