---
apiVersion: v1
kind: Service
metadata:
  name: treasurehunt-entrypoint
  namespace: default
spec:
  selector:
    serviceType: treasurehunt
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort