---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "treasurehunt.fullname" . }}-treasurehunt-config
  namespace: default
data:
  application.properties: |
    treasurehunt.max.attempts=5