---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "treasurehunt.fullname" . }}-treasurehunt-config
  namespace: default
data:
{{ (.Files.Glob "files/application.properties").AsConfig | indent 2 }}